# fly.toml app configuration file generated for silent-wood-211 on 2023-08-02T01:03:58-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "silent-wood-211"
primary_region = "yyz"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
